### ISSUE TITLE
fundgrube hack from terminal 😈

### ISSUE THREAD

**Issue by simonneutert** [RomanNess/fundgrube-crawler#1]
Hey Roman,

first of all: great job with the repo 👏 

Your repo inspired me to tinker a little with some CLI tools and I wanted to share the result with you ✌️ 

Tools:  
- [httpie](https://httpie.io/)
- [jq](https://stedolan.github.io/jq)

```bash
# save to file and zsh/bash that thing
URL_FUNDGRUBE_MAINZ='https://www.mediamarkt.de/de/data/fundgrube/api/postings?limit=100&offset=0&outletIds=418&recentFilter=outlets'
https ${URL_FUNDGRUBE_MAINZ} | jq '.postings | .[] | {name: .name, price: .price}'
```

**Comment by RomanNess** [comment]
Hi Simon,

Thanks for sharing and thanks for the feedback! I did not know about `httpie` but I immediately installed it. That looks like a real time saver. 😍

It's funny that I had also originally intended to use the problem with `curl` &  `jq` in a `bash` script and run it regularly with `crontab`. My exact use case is to query for new Postings regularly and to be alerted when new Postings are matched. To be honest, I went with the Golang solution because I haven't used it in years and I always wanted to try it out on my raspberry pi. 😅

Anyways, I'm a big friend of `bash` and you inspired me to quickly hack and share my initial idea. 
https://github.com/RomanNess/fundgrube-crawler/blob/main/.sh/fundgrube-crawler.sh
* The script also iterates over `outlets` since the API does not support `offset > 990`.
* Pagination is not supported because I have never seen >100 postings in an Outlet.
* It saves discovered deals in a "DB file" per search term and should only discover "new Postings". 

Run the thing in a `crontab` and alert about discovered postings via mail and it does fulfil the requirements of my initial use case. 🙂

If you intend to tinker with the API yourself I have documented my findings in https://github.com/RomanNess/fundgrube-crawler/tree/786291daa899c46ad4e44cd117802663b69a69ef#api-peculiarities.

**Comment by simonneutert** [comment]
lets add a "json differ" and pipe forward to https://github.com/caronc/apprise 🤯

**Comment by RomanNess** [comment]
I was thinking of good-old Gnu MailUtils for alerting from bash. 😅 
https://mailutils.org/manual/html_section/mail.html

**Comment by simonneutert** [comment]
marry me 🥳 
closed for public 🚧 http://t.me/simonneutert

**Comment by simonneutert** [comment]
https://github.com/simonneutert/fundgrube 🛒  
cron running 🥳
